/**
 * Bundled country → currency reference data (246 countries).
 *
 * Generated from the `world-countries` dataset (ISO 3166-1 / ISO 4217). Bundled
 * rather than fetched at runtime so the country picker works offline and never
 * blocks onboarding on a network call. To regenerate, re-run the generator in
 * the commit that introduced this file.
 *
 * `cur` is the ISO 4217 code; `symbol` is the local currency glyph. Formatting
 * precision (decimal places, separators, symbol position) is resolved in
 * `currency.ts` — the four tuned locales (USD/EUR/GBP/RSD) keep their hand-set
 * formats there; every other currency is formatted from sensible defaults.
 */

export type CountryInfo = {
  /** ISO 3166-1 alpha-2 */
  code: string;
  name: string;
  /** ISO 4217 currency code */
  cur: string;
  /** local currency symbol */
  symbol: string;
};

export const COUNTRIES: CountryInfo[] = [
  { code: "AF", name: "Afghanistan", cur: "AFN", symbol: "؋" },
  { code: "AX", name: "Åland Islands", cur: "EUR", symbol: "€" },
  { code: "AL", name: "Albania", cur: "ALL", symbol: "L" },
  { code: "DZ", name: "Algeria", cur: "DZD", symbol: "د.ج" },
  { code: "AS", name: "American Samoa", cur: "USD", symbol: "$" },
  { code: "AD", name: "Andorra", cur: "EUR", symbol: "€" },
  { code: "AO", name: "Angola", cur: "AOA", symbol: "Kz" },
  { code: "AI", name: "Anguilla", cur: "XCD", symbol: "$" },
  { code: "AG", name: "Antigua and Barbuda", cur: "XCD", symbol: "$" },
  { code: "AR", name: "Argentina", cur: "ARS", symbol: "$" },
  { code: "AM", name: "Armenia", cur: "AMD", symbol: "֏" },
  { code: "AW", name: "Aruba", cur: "AWG", symbol: "ƒ" },
  { code: "AU", name: "Australia", cur: "AUD", symbol: "$" },
  { code: "AT", name: "Austria", cur: "EUR", symbol: "€" },
  { code: "AZ", name: "Azerbaijan", cur: "AZN", symbol: "₼" },
  { code: "BS", name: "Bahamas", cur: "BSD", symbol: "$" },
  { code: "BH", name: "Bahrain", cur: "BHD", symbol: ".د.ب" },
  { code: "BD", name: "Bangladesh", cur: "BDT", symbol: "৳" },
  { code: "BB", name: "Barbados", cur: "BBD", symbol: "$" },
  { code: "BY", name: "Belarus", cur: "BYN", symbol: "Br" },
  { code: "BE", name: "Belgium", cur: "EUR", symbol: "€" },
  { code: "BZ", name: "Belize", cur: "BZD", symbol: "$" },
  { code: "BJ", name: "Benin", cur: "XOF", symbol: "Fr" },
  { code: "BM", name: "Bermuda", cur: "BMD", symbol: "$" },
  { code: "BT", name: "Bhutan", cur: "BTN", symbol: "Nu." },
  { code: "BO", name: "Bolivia", cur: "BOB", symbol: "Bs." },
  { code: "BA", name: "Bosnia and Herzegovina", cur: "BAM", symbol: "KM" },
  { code: "BW", name: "Botswana", cur: "BWP", symbol: "P" },
  { code: "BR", name: "Brazil", cur: "BRL", symbol: "R$" },
  { code: "IO", name: "British Indian Ocean Territory", cur: "USD", symbol: "$" },
  { code: "VG", name: "British Virgin Islands", cur: "USD", symbol: "$" },
  { code: "BN", name: "Brunei", cur: "BND", symbol: "$" },
  { code: "BG", name: "Bulgaria", cur: "BGN", symbol: "lv" },
  { code: "BF", name: "Burkina Faso", cur: "XOF", symbol: "Fr" },
  { code: "BI", name: "Burundi", cur: "BIF", symbol: "Fr" },
  { code: "KH", name: "Cambodia", cur: "KHR", symbol: "៛" },
  { code: "CM", name: "Cameroon", cur: "XAF", symbol: "Fr" },
  { code: "CA", name: "Canada", cur: "CAD", symbol: "$" },
  { code: "CV", name: "Cape Verde", cur: "CVE", symbol: "Esc" },
  { code: "BQ", name: "Caribbean Netherlands", cur: "USD", symbol: "$" },
  { code: "KY", name: "Cayman Islands", cur: "KYD", symbol: "$" },
  { code: "CF", name: "Central African Republic", cur: "XAF", symbol: "Fr" },
  { code: "TD", name: "Chad", cur: "XAF", symbol: "Fr" },
  { code: "CL", name: "Chile", cur: "CLP", symbol: "$" },
  { code: "CN", name: "China", cur: "CNY", symbol: "¥" },
  { code: "CX", name: "Christmas Island", cur: "AUD", symbol: "$" },
  { code: "CC", name: "Cocos (Keeling) Islands", cur: "AUD", symbol: "$" },
  { code: "CO", name: "Colombia", cur: "COP", symbol: "$" },
  { code: "KM", name: "Comoros", cur: "KMF", symbol: "Fr" },
  { code: "CK", name: "Cook Islands", cur: "CKD", symbol: "$" },
  { code: "CR", name: "Costa Rica", cur: "CRC", symbol: "₡" },
  { code: "HR", name: "Croatia", cur: "EUR", symbol: "€" },
  { code: "CU", name: "Cuba", cur: "CUC", symbol: "$" },
  { code: "CW", name: "Curaçao", cur: "ANG", symbol: "ƒ" },
  { code: "CY", name: "Cyprus", cur: "EUR", symbol: "€" },
  { code: "CZ", name: "Czechia", cur: "CZK", symbol: "Kč" },
  { code: "DK", name: "Denmark", cur: "DKK", symbol: "kr" },
  { code: "DJ", name: "Djibouti", cur: "DJF", symbol: "Fr" },
  { code: "DM", name: "Dominica", cur: "XCD", symbol: "$" },
  { code: "DO", name: "Dominican Republic", cur: "DOP", symbol: "$" },
  { code: "CD", name: "DR Congo", cur: "CDF", symbol: "FC" },
  { code: "EC", name: "Ecuador", cur: "USD", symbol: "$" },
  { code: "EG", name: "Egypt", cur: "EGP", symbol: "£" },
  { code: "SV", name: "El Salvador", cur: "USD", symbol: "$" },
  { code: "GQ", name: "Equatorial Guinea", cur: "XAF", symbol: "Fr" },
  { code: "ER", name: "Eritrea", cur: "ERN", symbol: "Nfk" },
  { code: "EE", name: "Estonia", cur: "EUR", symbol: "€" },
  { code: "SZ", name: "Eswatini", cur: "SZL", symbol: "L" },
  { code: "ET", name: "Ethiopia", cur: "ETB", symbol: "Br" },
  { code: "FK", name: "Falkland Islands", cur: "FKP", symbol: "£" },
  { code: "FO", name: "Faroe Islands", cur: "DKK", symbol: "kr" },
  { code: "FJ", name: "Fiji", cur: "FJD", symbol: "$" },
  { code: "FI", name: "Finland", cur: "EUR", symbol: "€" },
  { code: "FR", name: "France", cur: "EUR", symbol: "€" },
  { code: "GF", name: "French Guiana", cur: "EUR", symbol: "€" },
  { code: "PF", name: "French Polynesia", cur: "XPF", symbol: "₣" },
  { code: "TF", name: "French Southern and Antarctic Lands", cur: "EUR", symbol: "€" },
  { code: "GA", name: "Gabon", cur: "XAF", symbol: "Fr" },
  { code: "GM", name: "Gambia", cur: "GMD", symbol: "D" },
  { code: "GE", name: "Georgia", cur: "GEL", symbol: "₾" },
  { code: "DE", name: "Germany", cur: "EUR", symbol: "€" },
  { code: "GH", name: "Ghana", cur: "GHS", symbol: "₵" },
  { code: "GI", name: "Gibraltar", cur: "GIP", symbol: "£" },
  { code: "GR", name: "Greece", cur: "EUR", symbol: "€" },
  { code: "GL", name: "Greenland", cur: "DKK", symbol: "kr." },
  { code: "GD", name: "Grenada", cur: "XCD", symbol: "$" },
  { code: "GP", name: "Guadeloupe", cur: "EUR", symbol: "€" },
  { code: "GU", name: "Guam", cur: "USD", symbol: "$" },
  { code: "GT", name: "Guatemala", cur: "GTQ", symbol: "Q" },
  { code: "GG", name: "Guernsey", cur: "GBP", symbol: "£" },
  { code: "GN", name: "Guinea", cur: "GNF", symbol: "Fr" },
  { code: "GW", name: "Guinea-Bissau", cur: "XOF", symbol: "Fr" },
  { code: "GY", name: "Guyana", cur: "GYD", symbol: "$" },
  { code: "HT", name: "Haiti", cur: "HTG", symbol: "G" },
  { code: "HN", name: "Honduras", cur: "HNL", symbol: "L" },
  { code: "HK", name: "Hong Kong", cur: "HKD", symbol: "$" },
  { code: "HU", name: "Hungary", cur: "HUF", symbol: "Ft" },
  { code: "IS", name: "Iceland", cur: "ISK", symbol: "kr" },
  { code: "IN", name: "India", cur: "INR", symbol: "₹" },
  { code: "ID", name: "Indonesia", cur: "IDR", symbol: "Rp" },
  { code: "IR", name: "Iran", cur: "IRR", symbol: "﷼" },
  { code: "IQ", name: "Iraq", cur: "IQD", symbol: "ع.د" },
  { code: "IE", name: "Ireland", cur: "EUR", symbol: "€" },
  { code: "IM", name: "Isle of Man", cur: "GBP", symbol: "£" },
  { code: "IL", name: "Israel", cur: "ILS", symbol: "₪" },
  { code: "IT", name: "Italy", cur: "EUR", symbol: "€" },
  { code: "CI", name: "Ivory Coast", cur: "XOF", symbol: "Fr" },
  { code: "JM", name: "Jamaica", cur: "JMD", symbol: "$" },
  { code: "JP", name: "Japan", cur: "JPY", symbol: "¥" },
  { code: "JE", name: "Jersey", cur: "GBP", symbol: "£" },
  { code: "JO", name: "Jordan", cur: "JOD", symbol: "د.ا" },
  { code: "KZ", name: "Kazakhstan", cur: "KZT", symbol: "₸" },
  { code: "KE", name: "Kenya", cur: "KES", symbol: "Sh" },
  { code: "KI", name: "Kiribati", cur: "AUD", symbol: "$" },
  { code: "XK", name: "Kosovo", cur: "EUR", symbol: "€" },
  { code: "KW", name: "Kuwait", cur: "KWD", symbol: "د.ك" },
  { code: "KG", name: "Kyrgyzstan", cur: "KGS", symbol: "som" },
  { code: "LA", name: "Laos", cur: "LAK", symbol: "₭" },
  { code: "LV", name: "Latvia", cur: "EUR", symbol: "€" },
  { code: "LB", name: "Lebanon", cur: "LBP", symbol: "ل.ل" },
  { code: "LS", name: "Lesotho", cur: "LSL", symbol: "L" },
  { code: "LR", name: "Liberia", cur: "LRD", symbol: "$" },
  { code: "LY", name: "Libya", cur: "LYD", symbol: "ل.د" },
  { code: "LI", name: "Liechtenstein", cur: "CHF", symbol: "Fr" },
  { code: "LT", name: "Lithuania", cur: "EUR", symbol: "€" },
  { code: "LU", name: "Luxembourg", cur: "EUR", symbol: "€" },
  { code: "MO", name: "Macau", cur: "MOP", symbol: "P" },
  { code: "MG", name: "Madagascar", cur: "MGA", symbol: "Ar" },
  { code: "MW", name: "Malawi", cur: "MWK", symbol: "MK" },
  { code: "MY", name: "Malaysia", cur: "MYR", symbol: "RM" },
  { code: "MV", name: "Maldives", cur: "MVR", symbol: ".ރ" },
  { code: "ML", name: "Mali", cur: "XOF", symbol: "Fr" },
  { code: "MT", name: "Malta", cur: "EUR", symbol: "€" },
  { code: "MH", name: "Marshall Islands", cur: "USD", symbol: "$" },
  { code: "MQ", name: "Martinique", cur: "EUR", symbol: "€" },
  { code: "MR", name: "Mauritania", cur: "MRU", symbol: "UM" },
  { code: "MU", name: "Mauritius", cur: "MUR", symbol: "₨" },
  { code: "YT", name: "Mayotte", cur: "EUR", symbol: "€" },
  { code: "MX", name: "Mexico", cur: "MXN", symbol: "$" },
  { code: "MD", name: "Moldova", cur: "MDL", symbol: "L" },
  { code: "MC", name: "Monaco", cur: "EUR", symbol: "€" },
  { code: "MN", name: "Mongolia", cur: "MNT", symbol: "₮" },
  { code: "ME", name: "Montenegro", cur: "EUR", symbol: "€" },
  { code: "MS", name: "Montserrat", cur: "XCD", symbol: "$" },
  { code: "MA", name: "Morocco", cur: "MAD", symbol: "د.م." },
  { code: "MZ", name: "Mozambique", cur: "MZN", symbol: "MT" },
  { code: "MM", name: "Myanmar", cur: "MMK", symbol: "Ks" },
  { code: "NA", name: "Namibia", cur: "NAD", symbol: "$" },
  { code: "NR", name: "Nauru", cur: "AUD", symbol: "$" },
  { code: "NP", name: "Nepal", cur: "NPR", symbol: "₨" },
  { code: "NL", name: "Netherlands", cur: "EUR", symbol: "€" },
  { code: "NC", name: "New Caledonia", cur: "XPF", symbol: "₣" },
  { code: "NZ", name: "New Zealand", cur: "NZD", symbol: "$" },
  { code: "NI", name: "Nicaragua", cur: "NIO", symbol: "C$" },
  { code: "NE", name: "Niger", cur: "XOF", symbol: "Fr" },
  { code: "NG", name: "Nigeria", cur: "NGN", symbol: "₦" },
  { code: "NU", name: "Niue", cur: "NZD", symbol: "$" },
  { code: "NF", name: "Norfolk Island", cur: "AUD", symbol: "$" },
  { code: "KP", name: "North Korea", cur: "KPW", symbol: "₩" },
  { code: "MK", name: "North Macedonia", cur: "MKD", symbol: "den" },
  { code: "MP", name: "Northern Mariana Islands", cur: "USD", symbol: "$" },
  { code: "NO", name: "Norway", cur: "NOK", symbol: "kr" },
  { code: "OM", name: "Oman", cur: "OMR", symbol: "ر.ع." },
  { code: "PK", name: "Pakistan", cur: "PKR", symbol: "₨" },
  { code: "PW", name: "Palau", cur: "USD", symbol: "$" },
  { code: "PS", name: "Palestine", cur: "EGP", symbol: "E£" },
  { code: "PA", name: "Panama", cur: "PAB", symbol: "B/." },
  { code: "PG", name: "Papua New Guinea", cur: "PGK", symbol: "K" },
  { code: "PY", name: "Paraguay", cur: "PYG", symbol: "₲" },
  { code: "PE", name: "Peru", cur: "PEN", symbol: "S/." },
  { code: "PH", name: "Philippines", cur: "PHP", symbol: "₱" },
  { code: "PN", name: "Pitcairn Islands", cur: "NZD", symbol: "$" },
  { code: "PL", name: "Poland", cur: "PLN", symbol: "zł" },
  { code: "PT", name: "Portugal", cur: "EUR", symbol: "€" },
  { code: "PR", name: "Puerto Rico", cur: "USD", symbol: "$" },
  { code: "QA", name: "Qatar", cur: "QAR", symbol: "ر.ق" },
  { code: "CG", name: "Republic of the Congo", cur: "XAF", symbol: "Fr" },
  { code: "RE", name: "Réunion", cur: "EUR", symbol: "€" },
  { code: "RO", name: "Romania", cur: "RON", symbol: "lei" },
  { code: "RU", name: "Russia", cur: "RUB", symbol: "₽" },
  { code: "RW", name: "Rwanda", cur: "RWF", symbol: "Fr" },
  { code: "BL", name: "Saint Barthélemy", cur: "EUR", symbol: "€" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", cur: "GBP", symbol: "£" },
  { code: "KN", name: "Saint Kitts and Nevis", cur: "XCD", symbol: "$" },
  { code: "LC", name: "Saint Lucia", cur: "XCD", symbol: "$" },
  { code: "MF", name: "Saint Martin", cur: "EUR", symbol: "€" },
  { code: "PM", name: "Saint Pierre and Miquelon", cur: "EUR", symbol: "€" },
  { code: "VC", name: "Saint Vincent and the Grenadines", cur: "XCD", symbol: "$" },
  { code: "WS", name: "Samoa", cur: "WST", symbol: "T" },
  { code: "SM", name: "San Marino", cur: "EUR", symbol: "€" },
  { code: "ST", name: "São Tomé and Príncipe", cur: "STN", symbol: "Db" },
  { code: "SA", name: "Saudi Arabia", cur: "SAR", symbol: "ر.س" },
  { code: "SN", name: "Senegal", cur: "XOF", symbol: "Fr" },
  { code: "RS", name: "Serbia", cur: "RSD", symbol: "din." },
  { code: "SC", name: "Seychelles", cur: "SCR", symbol: "₨" },
  { code: "SL", name: "Sierra Leone", cur: "SLL", symbol: "Le" },
  { code: "SG", name: "Singapore", cur: "SGD", symbol: "$" },
  { code: "SX", name: "Sint Maarten", cur: "ANG", symbol: "ƒ" },
  { code: "SK", name: "Slovakia", cur: "EUR", symbol: "€" },
  { code: "SI", name: "Slovenia", cur: "EUR", symbol: "€" },
  { code: "SB", name: "Solomon Islands", cur: "SBD", symbol: "$" },
  { code: "SO", name: "Somalia", cur: "SOS", symbol: "Sh" },
  { code: "ZA", name: "South Africa", cur: "ZAR", symbol: "R" },
  { code: "GS", name: "South Georgia", cur: "SHP", symbol: "£" },
  { code: "KR", name: "South Korea", cur: "KRW", symbol: "₩" },
  { code: "SS", name: "South Sudan", cur: "SSP", symbol: "£" },
  { code: "ES", name: "Spain", cur: "EUR", symbol: "€" },
  { code: "LK", name: "Sri Lanka", cur: "LKR", symbol: "Rs  රු" },
  { code: "SD", name: "Sudan", cur: "SDG", symbol: "PT" },
  { code: "SR", name: "Suriname", cur: "SRD", symbol: "$" },
  { code: "SJ", name: "Svalbard and Jan Mayen", cur: "NOK", symbol: "kr" },
  { code: "SE", name: "Sweden", cur: "SEK", symbol: "kr" },
  { code: "CH", name: "Switzerland", cur: "CHF", symbol: "Fr." },
  { code: "SY", name: "Syria", cur: "SYP", symbol: "£" },
  { code: "TW", name: "Taiwan", cur: "TWD", symbol: "$" },
  { code: "TJ", name: "Tajikistan", cur: "TJS", symbol: "SM" },
  { code: "TZ", name: "Tanzania", cur: "TZS", symbol: "Sh" },
  { code: "TH", name: "Thailand", cur: "THB", symbol: "฿" },
  { code: "TL", name: "Timor-Leste", cur: "USD", symbol: "$" },
  { code: "TG", name: "Togo", cur: "XOF", symbol: "Fr" },
  { code: "TK", name: "Tokelau", cur: "NZD", symbol: "$" },
  { code: "TO", name: "Tonga", cur: "TOP", symbol: "T$" },
  { code: "TT", name: "Trinidad and Tobago", cur: "TTD", symbol: "$" },
  { code: "TN", name: "Tunisia", cur: "TND", symbol: "د.ت" },
  { code: "TR", name: "Türkiye", cur: "TRY", symbol: "₺" },
  { code: "TM", name: "Turkmenistan", cur: "TMT", symbol: "m" },
  { code: "TC", name: "Turks and Caicos Islands", cur: "USD", symbol: "$" },
  { code: "TV", name: "Tuvalu", cur: "AUD", symbol: "$" },
  { code: "UG", name: "Uganda", cur: "UGX", symbol: "Sh" },
  { code: "UA", name: "Ukraine", cur: "UAH", symbol: "₴" },
  { code: "AE", name: "United Arab Emirates", cur: "AED", symbol: "د.إ" },
  { code: "GB", name: "United Kingdom", cur: "GBP", symbol: "£" },
  { code: "US", name: "United States", cur: "USD", symbol: "$" },
  { code: "UM", name: "United States Minor Outlying Islands", cur: "USD", symbol: "$" },
  { code: "VI", name: "United States Virgin Islands", cur: "USD", symbol: "$" },
  { code: "UY", name: "Uruguay", cur: "UYU", symbol: "$" },
  { code: "UZ", name: "Uzbekistan", cur: "UZS", symbol: "so'm" },
  { code: "VU", name: "Vanuatu", cur: "VUV", symbol: "Vt" },
  { code: "VA", name: "Vatican City", cur: "EUR", symbol: "€" },
  { code: "VE", name: "Venezuela", cur: "VES", symbol: "Bs.S." },
  { code: "VN", name: "Vietnam", cur: "VND", symbol: "₫" },
  { code: "WF", name: "Wallis and Futuna", cur: "XPF", symbol: "₣" },
  { code: "EH", name: "Western Sahara", cur: "DZD", symbol: "دج" },
  { code: "YE", name: "Yemen", cur: "YER", symbol: "﷼" },
  { code: "ZM", name: "Zambia", cur: "ZMW", symbol: "ZK" },
  { code: "ZW", name: "Zimbabwe", cur: "BWP", symbol: "P" },
];

/** Country code → ISO 4217 currency code, for resolving a family currency. */
export const COUNTRY_CURRENCY: Record<string, string> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c.cur]),
);
